name: almas
description: A new Flutter project.

publish_to: 'none'

version: 3.0.7+8

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.0
  shared_preferences: ^2.0.15
  psr_base:
    git:
      url: https://github.com/plugcreator2002/psr_base.git
  http: ^0.13.5
  provider: ^6.0.4
  loader_overlay: ^2.1.0
  responsive_framework: ^0.2.0
  share_plus: ^6.2.0
  url_launcher: ^6.1.6
  font_awesome_flutter: ^10.2.1
  flutter_local_notifications: ^12.0.3
  device_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/red-tick.png
    - assets/blue-tick.png
    - assets/sounds/notification.mp3
    - assets/icons/
    - assets/gems/
    - assets/backgrounds/

  fonts:
    - family: icons
      fonts:
        - asset: fonts/icons.ttf
    - family: iranian-sans
      fonts:
        - asset: fonts/iranian-sans.ttf
    - family: mitra
      fonts:
        - asset: fonts/mitra.ttf
    - family: yekan
      fonts:
        - asset: fonts/yekan.ttf
    - family: nazanin
      fonts:
        - asset: fonts/nazanin.ttf
    - family: shablon
      fonts:
        - asset: fonts/shablon.ttf
    - family: ziba
      fonts:
        - asset: fonts/ziba.ttf
    - family: dirooz
      fonts:
        - asset: fonts/dirooz.ttf
    - family: entezaar
      fonts:
        - asset: fonts/entezaar.ttf
    - family: gandom
      fonts:
        - asset: fonts/gandom.ttf
    - family: nastaligh
      fonts:
        - asset: fonts/nastaligh.ttf
    - family: lalezar
      fonts:
        - asset: fonts/lalezar.ttf
    - family: maktabrita
      fonts:
        - asset: fonts/maktabrita.ttf
    - family: farsi
      fonts:
        - asset: fonts/farsi.ttf
    - family: ordibehesht
      fonts:
        - asset: fonts/ordibehesht.ttf
    - family: sahel
      fonts:
        - asset: fonts/sahel.ttf
    - family: vazir
      fonts:
        - asset: fonts/vazir.ttf
    - family: ruby
      fonts:
        - asset: fonts/ruby.ttf
    - family: samim
      fonts:
        - asset: fonts/samim.ttf